version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahjBH88rpud0
      MYSQL_DATABASE: wordpress
      MYSQL_USER: terada
      MYSQL_PASSWORD: yxsPbnPnVAEi
    # コンテナ名は変更すること
    container_name: wordpress_whitening_db

  wordpress:
    depends_on:
      - db
    build: .
    image: wp_template
    volumes:
      - ./html/.htaccess:/var/www/html/.htaccess
      - ./html:/var/www/html:delegated
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: terada
      WORDPRESS_DB_PASSWORD: yxsPbnPnVAEi
      WORDPRESS_DB_NAME: wordpress
    # コンテナ名は変更すること
    container_name: wordpress_whitening_web
